### ISSUE TITLE
Add ROIs attached to "number of fragments"/ "number of unidentified fragments" to ROIGroups restrictions

### ISSUE THREAD

**Issue by zarquon42b** [AnthroGraph/Phaleron-AppOntology#17]
Add ROIs attached to "number of fragments"/ "number of unidentified fragments" to suitable ROIGroups restrictions, so they can be queried in pathology sections as ROIs. This applies to all ROIGroups.

Example: The following classes should appear in the restrictions of `PhaleronVertebralColumnROIGroup`:

- Entire cervical vertebra
- Entire lumbar vertebra
- Entire thoracic vertebra
- Segment of sacrum

**Comment by cuboideum** [comment]
The following elements appear in the skeletal 'Inventory section hand and foot' (phaleron-si:AdultHandAndFoot) and apply to both hand and foot regions:

* Entire carpal or tarsal (phaleron-si:EntireCarpalOrTarsal)
* Entire left carpal or tarsal (phaleron-si:EntireLeftCarpalOrTarsal)
* Entire right carpal or tarsal (phaleron-si:EntireRightCarpalOrTarsal)
* Entire metacarpal or metatarsal (phaleron-si:EntireMetacarpalOrMetatarsal)
* Entire left metacarpal or metatarsal (phaleron-si:EntireLeftMetacarpalOrMetatarsal)
* Entire right metacarpal or metatarsal (phaleron-si:EntireRightMetacarpalOrMetatarsal)
* Entire phalanx (rdfbones:EntireBoneOrgan_fma321924)
* Entire left phalanx (hphaleron-si:EntireLeftPhalanx)
* Entire right phalanx (phaleron-si:EntireRightPhalanx)
* Entire hand or foot (phaleron-si:EntireHandOrFoot)
* Entire left hand or foot (phaleron-si:EntireLeftHandOrFoot)
* Entire right hand or foot (phaleron-si:EntireRightHandOrFoot)

The ROIGroups of the Phaleron-AppOntology that are used in the pathology module differentiate between 'Phaleron upper limb anatomical regions of interest group (phaleron-app:PhaleronUpperLimbROIGroup) and 'Phaleron lower limb anatomical regions of interest group' (phaleron-app:PhaleronLowerLimbROIGroup). This poses the problem that the ROIs listed above relate to both these groups.

I suggest to make the ROIs in question part of both groups with the aim to make them selectable in both tabs 'Arm and hand' and 'Leg and foot'. @zarquon42b: Would this be a good solution in terms of implementation? The downside of this solution would be the possibility to enter redundant information from both the 'Arm and hand' and the 'Leg and foot' tabs, respectively. Is there a better solution that would prevent this?

**Comment by cuboideum** [comment]
On branch file [phaleron-app.owl](https://github.com/AnthroGraph/Phaleron-AppOntology/blob/8f9f747d4b215e8286240f84fb087970e39504c2/phaleron-app.owl) now contains the updated 'Phaleron skull regions of interest group' and 'Phaleron skull articular regions of interest group'. @zarquon42b: You can use this for testing purposes.

**Comment by cuboideum** [comment]
@zarquon42b The changes from this pull request are also reflected in the robot branch.
